version: '3'
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes: 
      - "./server:/usr/src/server"
    environment: 
      REDIS_URI: redis://redis:6379
  redis:
    image: redis
    ports:
      - "6379:6379"