version: '3'
services:
  server:
    build: ./
    ports:
      - "4000:4000"
    volumes: 
      - "./:/usr/src/server"
    environment: 
      REDIS_URL: redis://redis:6379
  redis:
    image: redis
    ports:
      - "6379:6379"